### ISSUE TITLE
Localhost installation

### ISSUE THREAD

**Issue by jcamp** [oelna/microblog#3]
1. Installed on localhost (simple copy files across).
2. Updated Config with subdir with files.
3. Run and creates DB, but when you hit NEW tries and fails with:

Not Found
The requested URL /microblog/mb/login was not found on this server.
Apache/2.4.23 (Win64) PHP/5.6.25 Server at localhost Port 80

I can see the code looks at path(0) for 'login' - but path(0) is not login..

Any help appreciated.

**Comment by quantumbiotch** [comment]
Hello, did you figure this out?
Thanks so much!

**Comment by quantumbiotch** [comment]
figured it out, rename to -master in the htaccess folder... not the old name, just, "microblog" so do microblog-master

**Comment by oelna** [comment]
> Hello, did you figure this out? Thanks so much!

I'm not sure what issue you were having exactly, but I believe hosting on localhost should be relatively easy and I thought to have solved it in the past, yeah. Let me know if things are unclear.

**Comment by quantumbiotch** [comment]
YES, THANKS

**Comment by foxnoodles** [comment]
I'm getting internal sever error 500 on Mamps localhost when trying to run this.

DB file was automatically created so at least it ran through some of it. 

.htaccess looks like this. I've added RewriteCond %{SERVER_PORT} = 8888. becaus the default url for mamp is localhost:8888  

`AddCharset UTF-8 .xml
AddCharset UTF-8 .json

AddType application/atom+xml .xml
AddType application/json .json

<Files ~ "\.db$">
  <IfModule !mod_authz_core.c>
    Order allow,deny
    Deny from all
  </IfModule>
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
</Files>

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /microblog

# friendly URLs
RewriteRule ^feed/json/?$ feed/feed.json [L]
RewriteRule ^feed/atom/?$ feed/feed.xml [L]

RewriteCond %{SERVER_PORT} = 8888
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*) index.php [L]
</IfModule>`
