### ISSUE TITLE
Autolink - beware!

### ISSUE THREAD

**Issue by Agathon1** [oelna/microblog#5]
If you want to embed content into posts using a URL (videos, photos, etc) autolink will mess it up and it won't work.
There's reasons for it being a feature, this more of a tip for others, as I spent some time trying to figure out why I couldn't embed media.

The function [autolink](https://github.com/oelna/microblog/blob/de148409fe5024e662ee79a9d6a67368b727ccfb/functions.php#L9) is referenced [here](https://github.com/oelna/microblog/blob/de148409fe5024e662ee79a9d6a67368b727ccfb/timeline.inc.php#L44) and [here](https://github.com/oelna/microblog/blob/de148409fe5024e662ee79a9d6a67368b727ccfb/single.inc.php#L29).

To disable it :

```autolink($post['post_content'])``` -> ```$post['post_content']```

**Comment by oelna** [comment]
That's good feedback, thanks! It should probably have been some sort of config option. Or somebody smarter than me could make it so it doesn't break embedding.
